### ISSUE TITLE
你这个厉害了。

### ISSUE THREAD

**Issue by navy63** [laisimiao/Unet#1]
根据你说的glob.glob ，更改路径，用你这个跑成功了。

**Comment by navy63** [comment]
跑100个epoch,也就 几分钟，速度相当快
Epoch 00095: loss improved from 0.17578 to 0.17450, saving model to my_unet.hdf5
Epoch 96/100
24/24 [==============================] - 3s 134ms/step - loss: 0.1747 - acc: 0.9634 - val_loss: 0.3576 - val_acc: 0.8824

Epoch 00096: loss did not improve from 0.17450
Epoch 97/100
24/24 [==============================] - 3s 133ms/step - loss: 0.1741 - acc: 0.9640 - val_loss: 0.3497 - val_acc: 0.8772

Epoch 00097: loss improved from 0.17450 to 0.17413, saving model to my_unet.hdf5
Epoch 98/100
24/24 [==============================] - 3s 134ms/step - loss: 0.1731 - acc: 0.9646 - val_loss: 0.3572 - val_acc: 0.8838

Epoch 00098: loss improved from 0.17413 to 0.17314, saving model to my_unet.hdf5
Epoch 99/100
24/24 [==============================] - 3s 133ms/step - loss: 0.1728 - acc: 0.9649 - val_loss: 0.3799 - val_acc: 0.8875

Epoch 00099: loss improved from 0.17314 to 0.17283, saving model to my_unet.hdf5
Epoch 100/100
24/24 [==============================] - 3s 134ms/step - loss: 0.1732 - acc: 0.9646 - val_loss: 0.3445 - val_acc: 0.8744

Epoch 00100: loss did not improve from 0.17283
predict test data
30/30 [==============================] - 3s 97ms/step
array to image

**Comment by laisimiao** [comment]
其实还可以改一下，不用每步都保存模型

**Comment by navy63** [comment]
感觉这个已经相当不错了，也没有每步都保存，只有当loss下降的时候才会保存，为了展现最终的效果，跑了个500个epoch，这个数据在没有增强的情况下，还是相当的不错的。
Epoch 498/500
24/24 [==============================] - 3s 133ms/step - loss: 0.0078 - acc: 0.9970 - val_loss: 1.0983 - val_acc: 0.8833

Epoch 00498: loss did not improve from 0.00755
Epoch 499/500
24/24 [==============================] - 3s 133ms/step - loss: 0.0085 - acc: 0.9966 - val_loss: 1.0653 - val_acc: 0.8854

Epoch 00499: loss did not improve from 0.00755
