### ISSUE TITLE
How to make the .tif label? Could I use the labelme?

### ISSUE THREAD

**Issue by jonguo111** [laisimiao/Unet#2]
Excellent work!

**Comment by laisimiao** [comment]
Sorry, i apologize that i don't know how to generate the mask label, but i guess it should be done with some special software in this field. Besides, as i know, labelme is used to label bounding boxes in object detection field and make xml file like VOC format.

**Comment by jonguo111** [comment]
> Sorry, i apologize that i don't know how to generate the mask label, but i guess it should be done with some special software in this field. Besides, as i know, labelme is used to label bounding boxes in object detection field and make xml file like VOC format.

May I have your wechat or email?

**Comment by laisimiao** [comment]
My email:&nbsp;2625482530@qq.com



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jonguo111"<notifications@github.com&gt;; 
发送时间: 2020年1月5日(星期天) 晚上10:13
收件人: "laisimiao/Unet"<Unet@noreply.github.com&gt;; 
抄送: "2625482530"<2625482530@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [laisimiao/Unet] How to make the .tif label? Could I use the labelme? (#2)



 
Sorry, i apologize that i don't know how to generate the mask label, but i guess it should be done with some special software in this field. Besides, as i know, labelme is used to label bounding boxes in object detection field and make xml file like VOC format.
  
May I have your wechat or email?

**Comment by laisimiao** [comment]
> Sorry, i apologize that i don't know how to generate the mask label, but i guess it should be done with some special software in this field. Besides, as i know, labelme is used to label bounding boxes in object detection field and make xml file like VOC format.

not labelme, I refer to labelimg
